version: '3.1'

services:
#   be:
#     image: oficina5_be
#     deploy:
#       replicas: 1
#       resources:
#         limits:
#           cpus: "0.1"
#           memory: 50mb  
#     environment:
#         DATABASE_URL: "mongodb://mongo:27017/oficina5"
#     ports:
#        - 3001:3001
#     depends_on:
#       - mongo
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  

