version: '3.1'

services:
  # be:
  #   image: oficina5_be
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 50mb  
  #   environment:
  #       DATABASE_URL: "mongodb://db/mongo"
  #   ports:
  #      - 3001:3001
  #   depends_on:
  #     - db
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234

